export type Quote = { text: string; author?: string };

export const quotes: Quote[] = [
  // Bhagavad Gita / Krishna
  { text: "You have the right to action, never to its fruits.", author: "Bhagavad Gita 2.47" },
  { text: "Whatever happened, happened for the good.", author: "Bhagavad Gita" },
  { text: "Change is the only law of the universe.", author: "Krishna" },
  { text: "Set your heart upon your work, never on its reward.", author: "Bhagavad Gita" },
  { text: "Better one's own duty though imperfect, than another's well-performed.", author: "Bhagavad Gita 3.35" },
  { text: "The mind is restless, but it can be tamed by practice and detachment.", author: "Bhagavad Gita 6.35" },
  { text: "There never was a time when I did not exist, nor you.", author: "Krishna" },
  { text: "The wise grieve neither for the living nor for the dead.", author: "Bhagavad Gita 2.11" },
  { text: "The soul is neither born, nor does it die.", author: "Bhagavad Gita 2.20" },
  { text: "Pleasure from the senses seems like nectar at first, but is poison at the end.", author: "Bhagavad Gita 18.38" },
  { text: "One who sees inaction in action, and action in inaction, is wise.", author: "Bhagavad Gita 4.18" },
  { text: "Perform your obligatory duty — action is better than inaction.", author: "Bhagavad Gita 3.8" },
  { text: "He who has no attachments can truly love others.", author: "Krishna" },
  { text: "You came empty-handed and you will leave empty-handed.", author: "Krishna" },
  { text: "Surrender all your duties unto Me, and I shall protect you.", author: "Bhagavad Gita 18.66" },
  { text: "Yoga is the journey of the self, through the self, to the self.", author: "Bhagavad Gita 6.20" },
  { text: "Knowledge is better than mechanical practice.", author: "Bhagavad Gita 12.12" },
  { text: "The peace of God is with them whose mind and soul are in harmony.", author: "Bhagavad Gita" },
  { text: "Lust, anger, and greed are the three gates to self-destruction.", author: "Bhagavad Gita 16.21" },
  { text: "Curving back within myself I create again and again.", author: "Bhagavad Gita 9.8" },

  // Buddha & Buddhist
  { text: "The mind is everything. What you think, you become.", author: "Buddha" },
  { text: "Three things cannot be long hidden: the sun, the moon, and the truth.", author: "Buddha" },
  { text: "Peace comes from within. Do not seek it without.", author: "Buddha" },
  { text: "Holding onto anger is like drinking poison and expecting the other person to die.", author: "Buddha" },
  { text: "There is no path to happiness. Happiness is the path.", author: "Buddha" },
  { text: "Better than a thousand hollow words is one word that brings peace.", author: "Buddha" },
  { text: "You yourself, as much as anybody, deserve your love and affection.", author: "Buddha" },
  { text: "Do not dwell in the past, do not dream of the future, concentrate on the present.", author: "Buddha" },
  { text: "When words are both true and kind, they can change the world.", author: "Buddha" },
  { text: "Thousands of candles can be lit from a single candle — and its life will not be shortened.", author: "Buddha" },
  { text: "Pain is certain, suffering is optional.", author: "Buddhist Proverb" },
  { text: "We are shaped by our thoughts; we become what we think.", author: "Buddha" },
  { text: "If you light a lamp for someone else, it will also brighten your path.", author: "Buddha" },
  { text: "The way is not in the sky. The way is in the heart.", author: "Buddha" },
  { text: "When the student is ready, the teacher will appear.", author: "Buddhist Proverb" },

  // Rumi & Sufi
  { text: "What you seek is seeking you.", author: "Rumi" },
  { text: "The wound is the place where the Light enters you.", author: "Rumi" },
  { text: "Set your life on fire. Seek those who fan your flames.", author: "Rumi" },
  { text: "Don't grieve. Anything you lose comes round in another form.", author: "Rumi" },
  { text: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", author: "Rumi" },
  { text: "When you do things from your soul, you feel a river moving in you, a joy.", author: "Rumi" },
  { text: "Try not to resist the changes that come your way.", author: "Rumi" },
  { text: "You were born with wings — why prefer to crawl through life?", author: "Rumi" },
  { text: "The garden of the world has no limits except in your mind.", author: "Rumi" },
  { text: "Stop acting so small. You are the universe in ecstatic motion.", author: "Rumi" },
  { text: "Raise your words, not your voice. It is rain that grows flowers, not thunder.", author: "Rumi" },
  { text: "Out beyond ideas of wrongdoing and rightdoing, there is a field. I'll meet you there.", author: "Rumi" },
  { text: "Be like a tree and let the dead leaves drop.", author: "Rumi" },
  { text: "Wherever you stand, be the soul of that place.", author: "Rumi" },
  { text: "Let the beauty of what you love be what you do.", author: "Rumi" },

  // Greek philosophy
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
  { text: "Happiness depends upon ourselves.", author: "Aristotle" },
  { text: "It is the mark of an educated mind to entertain a thought without accepting it.", author: "Aristotle" },
  { text: "Patience is bitter, but its fruit is sweet.", author: "Aristotle" },
  { text: "Pleasure in the job puts perfection in the work.", author: "Aristotle" },
  { text: "The whole is greater than the sum of its parts.", author: "Aristotle" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
  { text: "The unexamined life is not worth living.", author: "Socrates" },
  { text: "I cannot teach anybody anything. I can only make them think.", author: "Socrates" },
  { text: "Be kind, for everyone you meet is fighting a hard battle.", author: "Plato" },
  { text: "The beginning is the most important part of the work.", author: "Plato" },
  { text: "Wise men speak because they have something to say; fools because they have to say something.", author: "Plato" },

  // Stoic / Marcus Aurelius
  { text: "You have power over your mind — not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius" },
  { text: "Waste no more time arguing what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "When you arise in the morning, think of what a precious privilege it is to be alive.", author: "Marcus Aurelius" },
  { text: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", author: "Marcus Aurelius" },
  { text: "If it is not right, do not do it; if it is not true, do not say it.", author: "Marcus Aurelius" },
  { text: "Accept the things to which fate binds you, and love the people whom fate brings you.", author: "Marcus Aurelius" },
  { text: "He who lives in harmony with himself lives in harmony with the universe.", author: "Marcus Aurelius" },
  { text: "Confine yourself to the present.", author: "Marcus Aurelius" },
  { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius" },

  // Lao Tzu / Tao / Eastern
  { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
  { text: "When I let go of what I am, I become what I might be.", author: "Lao Tzu" },
  { text: "Knowing others is intelligence; knowing yourself is true wisdom.", author: "Lao Tzu" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "A good traveler has no fixed plans and is not intent on arriving.", author: "Lao Tzu" },
  { text: "Silence is a source of great strength.", author: "Lao Tzu" },
  { text: "Mastering others is strength; mastering yourself is true power.", author: "Lao Tzu" },
  { text: "If you correct your mind, the rest of your life will fall into place.", author: "Lao Tzu" },
  { text: "Empty your mind. Be formless. Shapeless, like water.", author: "Bruce Lee" },
  { text: "Be water, my friend.", author: "Bruce Lee" },

  // Confucius
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
  { text: "When the goals cannot be reached, adjust the action steps, not the goals.", author: "Confucius" },
  { text: "Choose a job you love, and you will never have to work a day in your life.", author: "Confucius" },
  { text: "Real knowledge is to know the extent of one's ignorance.", author: "Confucius" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { text: "Wherever you go, go with all your heart.", author: "Confucius" },
  { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },

  // Modern motivational
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "The best time to plant a tree was twenty years ago. The second-best time is now.", author: "Chinese Proverb" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "Whether you think you can, or you think you can't — you're right.", author: "Henry Ford" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Your time is limited. Don't waste it living someone else's life.", author: "Steve Jobs" },
  { text: "Stay hungry. Stay foolish.", author: "Steve Jobs" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
  { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
  { text: "First they ignore you, then they laugh at you, then they fight you, then you win.", author: "Mahatma Gandhi" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { text: "The cave you fear to enter holds the treasure you seek.", author: "Joseph Campbell" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "It is never too late to be what you might have been.", author: "George Eliot" },
  { text: "Twenty years from now you will be more disappointed by the things you didn't do.", author: "Mark Twain" },
  { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { text: "Done is better than perfect.", author: "Sheryl Sandberg" },
  { text: "Either you run the day, or the day runs you.", author: "Jim Rohn" },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
  { text: "Genius is one percent inspiration, ninety-nine percent perspiration.", author: "Thomas Edison" },
  { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },

  // Inner / spiritual
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "Imagination is more important than knowledge.", author: "Albert Einstein" },
  { text: "Try not to become a man of success, but rather a man of value.", author: "Albert Einstein" },
  { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { text: "What lies behind us and before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "We don't see things as they are, we see them as we are.", author: "Anaïs Nin" },
  { text: "Comparison is the thief of joy.", author: "Theodore Roosevelt" },
  { text: "Suffering ceases to be suffering at the moment it finds a meaning.", author: "Viktor Frankl" },
  { text: "When we are no longer able to change a situation, we are challenged to change ourselves.", author: "Viktor Frankl" },
  { text: "Between stimulus and response there is a space. In that space is our power to choose.", author: "Viktor Frankl" },
  { text: "Until you make the unconscious conscious, it will direct your life and you will call it fate.", author: "Carl Jung" },
  { text: "I am not what happened to me, I am what I choose to become.", author: "Carl Jung" },
  { text: "Who looks outside, dreams; who looks inside, awakes.", author: "Carl Jung" },

  // Resilience / perseverance
  { text: "Hard times don't create heroes — they reveal the hero within us.", author: "Bob Riley" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "If you are going through hell, keep going.", author: "Winston Churchill" },
  { text: "When everything seems against you, remember the airplane takes off against the wind.", author: "Henry Ford" },
  { text: "Tough times never last, but tough people do.", author: "Robert H. Schuller" },
  { text: "Out of difficulties grow miracles.", author: "Jean de La Bruyère" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "Storms make trees take deeper roots.", author: "Dolly Parton" },
  { text: "The world breaks everyone, and afterward many are strong at the broken places.", author: "Ernest Hemingway" },
  { text: "Whatever you are, be a good one.", author: "Abraham Lincoln" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { text: "The man on top of the mountain didn't fall there.", author: "Vince Lombardi" },

  // Big / longer reflective quotes
  { text: "Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did do. Throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover.", author: "Mark Twain" },
  { text: "You will be the same person in five years as you are today except for the people you meet and the books you read.", author: "Charlie Tremendous Jones" },
  { text: "If you can keep your head when all about you are losing theirs and blaming it on you — yours is the Earth and everything that's in it.", author: "Rudyard Kipling" },
  { text: "Holding on to anger, resentment and hurt only gives you tense muscles, a headache, and a sore jaw. Forgiveness is letting go and freeing yourself.", author: "Unknown" },
  { text: "Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.", author: "Rumi" },
  { text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain" },
  { text: "If you want to know your past life, look into your present condition. If you want to know your future life, look at your present actions.", author: "Buddha" },
  { text: "Watch your thoughts; they become words. Watch your words; they become actions. Watch your actions; they become habits. Watch your habits; they become character.", author: "Lao Tzu" },
  { text: "Be patient with yourself. Nothing in nature blooms all year — and neither will you.", author: "Unknown" },
  { text: "Sometimes the bravest and most important thing you can do is just show up.", author: "Brené Brown" },
];
